---
title: "How to contribute to jsar"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to contribute to jsar}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# Contribution Guidelines 

<sup>jsar contributing guidelines 0.1.0</sup>

**Everyone is welcome to contribute to the code, documentation, testing, and suggestions.**

The `jsar` package is designed to be beginner-friendly. Whether you're new to open-source, coding, or GitHub, we encourage you to try submitting pull requests (PRs). You can contribute by exploring the code, improving documentation, or enhancing tests. There are always typos to fix, docs to clarify, details to add, code to document, and tests to write. Even the smallest PRs are valuable and appreciated.

Getting started is the most important step! You’ll discover a whole new world of collaboration and learning. Fork [jsar repo](https://github.com/SShamiri/jsar), make some changes, and submit them. We’ll work together to make it the best it can be!


## I want to help, but I don't know where to start
Check out the [issue section](https://github.com/SShamiri/jsar/issues) to find features, ideas, or bugs that you can work on. You can also open a new issue just to let us know you’re interested in helping out. We’ll gladly suggest tasks that match your skill level.

## File issues 
If you’ve found a bug, first illustrate the bug with a minimal example. Then file it on the GitHub repo of the [issue section](https://github.com/SShamiri/jsar/issues).

## Contribute documentation 
Documentation is a high priority for jsar and pull requests to correct or improve documentation are welcome. The most important thing to know is that `jsar` packages use `roxygen2`; this means that documentation is found in the R code close to the source of each function. 

## Contribute code 
If you are a more experienced programmer, you might want to help out with the package development. Before you do a pull request, you should always file an issue and make sure someone from the `jsar` team agrees that it’s a problem, and is happy with your basic proposal for fixing it. We don’t want you to spend a bunch of time on something that we don’t think is a good idea.


## Contribute idea
Don’t let impostor syndrome hold you back! Every suggestion and opinion is valuable. Even if it’s just a thought, your feedback is always welcome. Go to the [issue section](https://github.com/SShamiri/jsar/issues) and to add your idea.
